#ifndef DATABASEMANAGE_GLOBAL_H
#define DATABASEMANAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASEMANAGE_LIBRARY)
#   define DATABASEMANAGE_EXPORT Q_DECL_EXPORT
#else
#   define DATABASEMANAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASEMANAGE_GLOBAL_H
